apiVersion: v1
kind: Pod
metadata:
 name: application
 labels:
   app: web
spec:
 containers:
   – name: application
     image: babu479/application:latest
     ports:
       – containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: Service
spec:
  selector:
    app: application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
