---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: default
  labels:
    app: application
spec:
  externalTrafficPolicy: Local
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: application
  type: NodePort
